### ISSUE TITLE
hi, it can't work on macOS Mojave! 

### ISSUE THREAD

**Issue by NotsayJustdo** [mologie/NVWebDriverLibValFix#8] opened 2018-10-14 23:23 UTC
@mologie

**Comment by mologie** [comment] 2018-10-14 23:25
Working as intended: This plugin addresses an issue in macOS 10.12 Sierra; the issue was fixed in 10.13 and later. (In any case, WhateverGreen has superseded this project: https://github.com/acidanthera/WhateverGreen)

**Closed as completed by mologie** 2018-10-14 23:25 UTC
Labels: question, wontfix
