### ISSUE TITLE
High Sierra Support

### ISSUE THREAD

**Issue by ciak2009** [mologie/NVWebDriverLibValFix#6] opened 2017-09-16 21:53 UTC
Will you be updating this for High Sierra, this is the most amazing kext I've ever used and it singlehandedly made my system stop crashing and losing video output every few days!

Thanks for this awesome patch!!!

-Caleb

**Comment by mologie** [comment] 2017-09-16 22:10
Hi Caleb, yes, I'll provide an update if one is needed. Keep in mind that NVIDIA takes a few days/weeks to release a web driver update, so you may want hold off updating to High Sierra until a new web driver is available and this kext is compatible.

I'll leave this ticket open for visibility and close it when the support question can be answered.

**Comment by ciak2009** [comment] 2017-09-16 22:11
You're a legend, I'll definitely be holding off for now, I cannot wait to see how High Sierra does with dual GPUs now that the window server is going to use Metal. I have two 980Ti's ;)

**Comment by MysticalOS** [comment] 2017-09-27 08:08
Just to be clear, it's NOT needed on high sierra and in fact this should be uninstalled on high sierra.

they refactored the 10.13 driver and it now plays nice nice with libval. no hacks are needed any more. little  snitch, ibooks, etc all work good out of box with web driver.

**Comment by paulotex** [comment] 2017-09-28 13:05
Hi guys. Just confirming that my system (High Sierra, X299 Mobo, 7820X processor, GTX 1070 and GT710) really needs this kext with the Web Drivers. Without the kext, the system gets stuck at "gIOScreenLockstate".

So not only it works with 10.13, it is actually needed in my case. (Note that Lilu did not help.)

So thanks a lot for creating this, it is really a great help!

**Comment by OdNairy** [comment] 2017-09-28 13:15
@paulotex Have you need to use this kext in Sierra 10.12?

**Comment by paulotex** [comment] 2017-09-28 13:55
@OdNairy: I did not have this system built before, so I didn't test it under 10.12. However I had a different system under 10.12 (an older i5-2400 with a GT640), and I did not need the kext for that system.

**Comment by edgard** [comment] 2017-09-28 19:49
Seems that using the latest webdrivers from Nvidia for High Sierra does not require this anymore. I'm currently running without issues.

**Comment by MysticalOS** [comment] 2017-09-28 19:54
Right.  the issue is that window server itself now uses libvalidation. that's why people can't even boot on 10.13 if their drivers are tainted.

unmodified drivers with no injection or alteration/patching etc don't need this, but people using LiLu or other tools that do modify their kexts will immediately find their system unbootable without this or they won't be able to boot cause they'll black screen as soon as window server tries to start.

Since a LOT of hackintoshers inject into their kexts or patch em for whatever reason, this became a whole lot more popular for those users. But for users, even on hacks who are leaving their kexts vanilla no longer need this is correct.

**Comment by paulotex** [comment] 2017-09-29 08:36
@MysticalOS, I am using VoodooHDA, which installs in /S/L/E. All others kexts are inject through Clover. Would this VoodooHDA cause a tainted kext situation? If yes, then that explains my need for this kext.

**Comment by edgard** [comment] 2017-09-29 12:53
I do use Lilu (for AppleALC) and have no problem booting.

Maybe it's because I don't put the kexts on S/L/E? I use it on Clover kexts/other folder.

**Comment by ciak2009** [comment] 2017-10-04 03:45
Now that we are a bit down the line on this, if we don't modify our video card kexts, is there a downside to continuing to use this rather than dumping it all together? 

Thanks!

**Comment by mologie** [comment] 2017-12-12 14:50
Hi everyone! It is correct that under macOS High Sierra, this extension is no longer required, because Apple and NVIDIA have made changes to how graphics drivers and their userspace components are loaded.

If you've still got the extension installed on High Sierra (it won't break things, but it won't do any good either,) try removing it and check if your system still works.

The one exception to the above are modified environments where library validation is triggered, like @MysticalOS explained.

For those on macOS Sierra and those affected by the library validation problem, check out the excellent extension NvidiaGraphicsFixup, into which @vit9696 included this extension's patches on the basis of Lilu:

https://sourceforge.net/projects/nvidiagraphicsfixup/

**Closed by mologie** 2017-12-12 14:50 UTC
Labels: question
